# -*- coding: utf-8 -*-
"""import.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tV3qY7C6wenJVlIWZUW9-nvA03Lq-mot
"""

from rdkit.Chem import Descriptors
from rdkit.Chem import AllChem as ch
from rdkit.Chem import Draw as d
from rdkit import DataStructs
import pandas as pd
from rdkit.Chem import rdMolDescriptors as rdescriptors
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
import csv
from rdkit.SimDivFilters.rdSimDivPickers import MaxMinPicker
import sklearn
from rdkit.Chem import PandasTools, Descriptors, MolFromSmiles
from pandas import DataFrame
from sklearn.model_selection import train_test_split
from sklearn import svm
import numpy as np
from sklearn.metrics import mean_squared_error
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestRegressor, AdaBoostRegressor, GradientBoostingRegressor
from rdkit import Chem
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
import torch
from rdkit import Chem
from rdkit.Chem import AllChem
from rdkit.Chem import Draw
from rdkit.Chem.Draw import IPythonConsole
from torch_geometric.data import Data
from torch_geometric.nn import GCNConv
import rdkit.Chem as ch
import rdkit.Chem as Chem