# -*- coding: utf-8 -*-
"""pip install.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1k1vQbXllcob0IkuKQ0TKMQlxmI9JdHPW
"""

pip install rdkit
pip install pandas
pip install matplotlib
pip install scikit-learn
pip install torch-geometric